# Numpy

NumPy is a general purpose array processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is fundamental package for scientific computing with Python.

### Array

An array is a data structure that stores the same data type.

In [9]:
import numpy as np

In [10]:
list=[1,2,3,4,5]
arr=np.array(list)

In [11]:
type(arr)

numpy.ndarray

In [12]:
arr

array([1, 2, 3, 4, 5])

In [13]:
print(arr)

[1 2 3 4 5]


In [14]:
arr.shape

(5,)

In [15]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
list3=[11,12,13,14,15]

arr=np.array([list1,list2,list3])

In [16]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [17]:
arr.shape

(3, 5)

In [18]:
arr.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [19]:
arr.shape

(3, 5)

### Indexing

In [21]:
arr=np.array([1,2,3,4,5,6,7,8])

In [22]:
arr[5]

6

In [23]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [24]:
arr=np.array([[1,2,3,4,5],
             [6,7,8,9,10],
             [11,12,13,14,15]])

In [25]:
arr[1:,3:]

array([[ 9, 10],
       [14, 15]])

In [26]:
arr[:,2:]

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15]])

In [27]:
arr=np.arange(0,10)

In [28]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arr=np.arange(0,10,step=2) 

In [30]:
arr

array([0, 2, 4, 6, 8])

In [31]:
np.linspace(1,10,25)

array([ 1.   ,  1.375,  1.75 ,  2.125,  2.5  ,  2.875,  3.25 ,  3.625,
        4.   ,  4.375,  4.75 ,  5.125,  5.5  ,  5.875,  6.25 ,  6.625,
        7.   ,  7.375,  7.75 ,  8.125,  8.5  ,  8.875,  9.25 ,  9.625,
       10.   ])

In [32]:
arr[3:]=45

In [33]:
arr

array([ 0,  2,  4, 45, 45])

In [34]:
arr1=arr
arr1

array([ 0,  2,  4, 45, 45])

In [35]:
arr1[3:]=500
print(arr1)

[  0   2   4 500 500]


In [36]:
arr=[0, 2, 4, 6, 8, 10]
arr1=[0, 2, 4, 6, 500, 500]

In [37]:
arr1=arr.copy()
arr1

[0, 2, 4, 6, 8, 10]

In [41]:
### Exploratory Data Analysis Conditions

val=4

arr*2

[0, 2, 4, 6, 8, 10, 0, 2, 4, 6, 8, 10]

In [43]:
np.arange(0,10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [45]:
arr1=np.arange(0,10).reshape(5,2)
arr1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [51]:
arr2=np.arange(0,10).reshape(5,2)
arr2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [53]:
arr1*arr2

array([[ 0,  1],
       [ 4,  9],
       [16, 25],
       [36, 49],
       [64, 81]])

In [55]:
np.ones(4,dtype=float)

array([1., 1., 1., 1.])

In [57]:
np.ones((2,6),dtype=int)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [67]:
arr3=np.random.rand(3,6)
arr3

array([[0.63010647, 0.47233592, 0.90425293, 0.86157413, 0.51321268,
        0.86253719],
       [0.93478687, 0.27805316, 0.18938069, 0.76769713, 0.53794128,
        0.31051033],
       [0.77888451, 0.22110445, 0.23052416, 0.26072525, 0.90423609,
        0.45196983]])

In [79]:
import seaborn as sns
import pandas as pd

In [85]:
sns.distplot(pd.DataFrame(arr3.reshape(6,3)))

C:\Users\adity\AppData\Local\Temp\ipykernel_804\2550522031.py:1: UserWarning: 

`distplot` is a deprecated function and will be removed in seaborn v0.14.0.

Please adapt your code to use either `displot` (a figure-level function with
similar flexibility) or `histplot` (an axes-level function for histograms).

For a guide to updating your code to use the new functions, please see
https://gist.github.com/mwaskom/de44147ed2974457ad6372750bbe5751

  sns.distplot(pd.DataFrame(arr3.reshape(6,3)))


<Axes: ylabel='Density'>

In [87]:
np.random.randint(0,100,8).reshape(4,2)

array([[10, 68],
       [64,  2],
       [14, 27],
       [18, 43]])

In [89]:
np.random.random_sample((2,15))

array([[0.15566595, 0.58304537, 0.5017036 , 0.75493222, 0.14063953,
        0.77752178, 0.8595699 , 0.59665043, 0.6310934 , 0.44728373,
        0.4926776 , 0.67778536, 0.03100707, 0.14177082, 0.82181498],
       [0.46850842, 0.05954376, 0.93089363, 0.62840371, 0.54938831,
        0.71018274, 0.10820461, 0.66170502, 0.72309405, 0.28356057,
        0.69167197, 0.271259  , 0.95454746, 0.41178509, 0.79536808]])